# Generated by Django 5.2.7 on 2025-10-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_empleado_pagoempleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
